name: CI

# Use runs on `ubuntu-latest-8-cores`. All of our self hosted runners use this tag.
# Our runners pick up jobs first, and if all our runners are being used or are down
# it will automatically back up to using GitHub hosted runners.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_rust:
    strategy:
      matrix:
        runner: [blacksmith-staging-4vcpu-ubuntu-2204, blacksmith-staging, nscloud-ubuntu-22.04-amd64-4x16]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Run tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Install dependencies
        run: |
          lscpu
          sudo apt-get update
          sudo apt-get install -y fio git build-essential flex bison libssl-dev libelf-dev cmake protobuf-compiler

      # - name: Clone and test Substrate
      #   run: |
      #     git clone https://github.com/paritytech/substrate.git
      #     cd substrate
      #     rustup target add wasm32-unknown-unknown
      #     time cargo test
      #     cd ..

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy, llvm-tools-preview
          cache: false

      # - name: Install Rust 1.78
      #   run: |
      #     rustup install 1.78
      #     rustup default 1.78
      #     rustup component add rustfmt --toolchain 1.78

      # - name: Clone and test rust-analyzer
      #   run: |
      #     git clone https://github.com/rust-analyzer/rust-analyzer.git
      #     cd rust-analyzer
      #     rustup component add rust-src --toolchain 1.78
      #     time cargo test
      #     cd ..

      # - name: Clone and test Rocket
      #   run: |
      #     git clone https://github.com/SergioBenitez/Rocket.git
      #     cd Rocket
      #     time cargo test
      #     cd ..

      # - name: Clone and test Actix
      #   run: |
      #     git clone https://github.com/actix/actix-web.git
      #     cd actix-web
      #     time cargo test
      #     cd ..

      # - name: Clone and build Deno
      #   run: |
      #     git clone https://github.com/denoland/deno.git
      #     cd deno
      #     time cargo build --release
      #     cd ..

      # - name: Clone and build Redis
      #   run: |
      #     git clone https://github.com/redis/redis.git
      #     cd redis
      #     time make -j32
      #     cd ..

      # - name: Clone Linux repository
      #   run: |
      #     git clone --depth=1 https://github.com/torvalds/linux.git

      # - name: Build Linux kernel
      #   run: |
      #     cd linux
      #     make defconfig
      #     time make -j32

      - name: Install fio
        run: |
          sudo apt-get install -y fio

      - name: Measure random read IO disk performance
        run: |
          fio --name=random-read --ioengine=posixaio --rw=randread --bs=4k --numjobs=1 --size=4g --time_based --runtime=60 --ramp_time=10 --group_reporting

      - name: Measure random write IO disk performance
        run: |
          fio --name=random-write --ioengine=posixaio --rw=randwrite --bs=4k --numjobs=1 --size=4g --time_based --runtime=60 --ramp_time=10 --group_reporting

      - name: Measure sequential read IO disk performance
        run: |
          fio --name=sequential-read --ioengine=posixaio --rw=read --bs=1m --numjobs=1 --size=4g --time_based --runtime=60 --ramp_time=10 --group_reporting

      - name: Measure sequential write IO disk performance
        run: |
          fio --name=sequential-write --ioengine=posixaio --rw=write --bs=1m --numjobs=1 --size=4g --time_based --runtime=60 --ramp_time=10 --group_reporting

      - uses: actions/checkout@v4

      - name: Install grcov
        run: if ! which grcov; then cargo install grcov; fi

      - name: Install llvm-tools-preview
        run: if ! which llvm-tools-preview; then rustup component add llvm-tools-preview; fi

      - name: Install pkg-config
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config

      - name: Test quadratic-core
        env:
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage
          RUSTC_BOOTSTRAP: 1
        run: |
          cd quadratic-core
          time cargo test

      - name: Generate coverage for quadratic-core
        env:
          RUSTC_BOOTSTRAP: 1
        run: |
          grcov $(find . -name "grcov-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --ignore "/*" \
            --ignore "./src/wasm_bindings/*" \
            --ignore "./src/bin/*" \
            --ignore "./docker/*" \
            -o lcov.info

      - name: Test quadratic-multiplayer
        env:
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage
          RUSTC_BOOTSTRAP: 1
        run: |
          cd quadratic-multiplayer
          time npm run docker:test

      - name: Generate coverage quadratic-multiplayer
        env:
          RUSTC_BOOTSTRAP: 1
        run: |
          grcov $(find . -name "grcov-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --ignore "/*" \
            --ignore "./src/wasm_bindings/*" \
            --ignore "./src/bin/*" \
            --ignore "./docker/*" \
            --ignore "./../docker/*" \
            -o lcov.info

  test_unit:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: "nightly"

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build quadratic-core
        run: |
          npm run build:wasm:javascript

      - name: Build quadratic-rust-client
        run: |
          npm run build:rust-client

      - name: Build python
        run: |
          npm run build:python

      - name: Run npm test:ts in quadratic-client
        run: |
          npm install
          npm run test:ts

  test_python:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"
          cache: "pip"

      - name: Test python
        run: |
          cd quadratic-kernels/python-wasm
          npm run test

  test_api:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run npm test:ci in quadratic-api
        run: |
          npm install
          cd quadratic-api
          npm run docker:test:ci

  lint_rust:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
          cache: false

      - name: Run cargo clippy in quadratic-core
        run: |
          cd quadratic-core
          cargo clippy -- -D warnings

  lint:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          cache: false
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build wasm core
        run: |
          npm run build:rust-client
          cd quadratic-client
          npm run build:wasm:javascript:dev
          npm run build:wasm:types

      - name: Lint quadratic-client
        run: |
          npm install
          cd quadratic-client
          npm run lint:prettier
          npm run lint:eslint
          npm run lint:ts
